title: PreserveDB
description: The Preservia Content Database
logo: "site-logo.png"
remote_theme: just-the-docs/just-the-docs
color-scheme: dark

url: https://preservia.github.io
baseurl: /database

search_enabled: true

aux_links:
  "Nintendo Switch Port Archive":
    - "/ports"
  "The 3DS Font Library":
    - "/fonts"


nav_enabled: true
nav_sort: case_sensitive
