title: PreserveDB
description: The PreserveDB
remote_theme: just-the-docs/just-the-docs
just_the_docs:
  custom_css:
    - docs/css/custom.css

url: https://preservia.github.io
baseurl: /database

color_scheme: light
search_enabled: true

aux_links:
  "Nintendo Switch Port Archive":
    - "/ports"
  "The 3DS Font Library":
    - "/fonts"


nav_enabled: true
nav_sort: case_sensitive
nav:
  - title: Nintendo Switch Port Archive
    url: /contents/
    children:
      - title: Ship of Harkinian
        url: /contents/soh.md
