title: PreserveDB
description: The PreserveDB
remote_theme: just-the-docs/just-the-docs

url: https://preservia.github.io
baseurl: /database

color_scheme: light
search_enabled: true

aux_links:
  "Nintendo Switch Port Archive":
    - "/ports"
  "The 3DS Font Library":
    - "/fonts"
